version: '3'
services:
  nginx:
    container_name: nginx-phpmyadmin
    image: eterlabs/nginx-php72
    volumes:
      - ./phpmyadmin:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/php.ini:/etc/php/7.2/fpm/php.ini
      - ./config/eterlabs.dev.pem:/etc/ssl/eterlabs.dev.pem
      - ./config/eterlabs.dev.key:/etc/ssl/eterlabs.dev.key
    ports:
      - "8081:80"
      - "8082:443"
    extra_hosts:
      - "host.docker.local:host-gateway"