version: '3'
services:
  nginx:
    container_name: nginx-telcelcondesa
    image: registry.digitalocean.com/eterlabs/nginx-php72
    volumes:
      - ./code:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/php.ini:/etc/php/7.2/fpm/php.ini
    ports:
      - "8081:80"